### ISSUE TITLE
Features still lacking for write UI

### ISSUE THREAD

**Issue by ShootingStar91** [nowcommunity/nowdatabase#114]
- [x] Notification on success/error **(Mostly implemented, checking as done)**
- [x] List of validation errors (should probably be available longer than just as a hover notification, so that user can reopen it to view all errors) **(Implemented, checking as done. Notification persistence related to #69** (_nice_) **)**
- [x] Time Unit editing UI (sequence etc?) **(Implemented, checking as done)**
- [x] Some data types cannot yet be created, because the query is not skipped correctly for 'new' id (also check default values exist) **(Implemented, checking as done)**
- [x] Add route & service for sequence and use it in time unit editing **(Implemented, checking as done)**
- [x] Prevent leaving view when in edit mode **(Not implemented, tracked in #477. Checking this as done as there exists an issue about it)**
- [x] Adding synonyms **(Implemented, checking as done)**
- [x] Editing fields inside a table **(If understood correctly, editing should be possible in Table-view which is not wanted. Checking as Not planning)**
- [x] Validating new items created via forms at the creation **(Implemented, checking as done)**
- [x] Logic for creating new species in form: There should be some kind of a "copy from existing species" option **(Not implemented but tracked in #146 and #373, checking as done as it is tracked)**
- [x] Delete button should be inside detail view **(Implemented, checking as done)** 
- [x] Redirect user to the newly created item. This is done in locality, but perhaps general solution would work best **(Implemented, checking as done)**

**Comment by iritmaximus** [comment]
All features are implemented, tracked in a separate issue or not planned.
