### ISSUE TITLE
TODO list for first production read version

### ISSUE THREAD

**Issue by ShootingStar91** [nowcommunity/nowdatabase#115]
- [x] Make all edit buttons hidden by default, they should show only when a certain environment variable is set. Also check for the correct user role.
- [x] The editing routes must be disabled also in backend with the env variable.
- [x] Password can be changed
- [x] First login prompts password change
- [x] Think about login expiration time & handling cases in frontend where login expires (possibly https://stackoverflow.com/a/77211246/10958592)
- [x] Last login info in people table should be formatted with the same code as in the tab
- [x] Exporting with included species/localities
- [x] Better deployment pipeline

- [x] Calculated values #85 (partly done) **(is done)**
- [x] Email sending **(implemented, not tested, checking as done)**
- [x] Add more info to people-table: User data, like initials and role **(done)**
- [x] Error reporting (sentry) **(is tracked in #70, checking as done)**
- [x] Better filters (fuzzy, number ranges etc) **(partly tracked in #377, partly already implemented)**
- [x] Cross-table filtering **(Implemented as cross-search)**

**Comment by iritmaximus** [comment]
All done, closing.
